name: CI python

on:
  push:
    paths-ignore:
      - "README.md"

jobs:
  build_and_test_job:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_DB: "baracoda_test"
        options: >-
          --health-cmd pg_isready
          --health-interval 20s
          --health-timeout 10s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/Pipfile') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dependencies
        run: |
          pipenv install --dev --ignore-pipfile --system --deploy
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Run mypy
        run: |
          mypy .
      - name: Create test database and table and insert test data
        run: |
        env:
          FLASK_APP: baracoda
          SETTINGS_PATH: config/test.py
      - name: Test with pytest
        run: |
          python -m pytest -vsx
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
